### ISSUE TITLE
Failed to parse source map from... Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by vsevdrob** [EthWorks/useDApp#521]
The problem is when I run `yarn start` there are some warnings occur as:
```bash
...

WARNING in ./node_modules/@usedapp/core/dist/esm/src/providers/transactions/reducer.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/mac/Desktop/react-django-nft-marketplace/react_django_nft_marketplace/frontend/frontend/node_modules/@usedapp/core/dist/esm/src/providers/transactions/reducer.js.map' file: Error: ENOENT: no such file or directory, open '/Users/mac/Desktop/react-django-nft-marketplace/react_django_nft_marketplace/frontend/frontend/node_modules/@usedapp/core/dist/esm/src/providers/transactions/reducer.js.map'
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/transactions/provider.js 8:0-47 23:46-64
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/DAppProvider.js 8:0-62 50:29-48
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/index.js 1:0-31 1:0-31
 @ ./node_modules/@usedapp/core/dist/esm/src/index.js 2:0-28 2:0-28
 @ ./src/App.tsx 5:0-54 11:30-42 13:24-37 13:39-54
 @ ./src/index.tsx 7:0-24 11:33-36

102 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.68.0 compiled with 102 warnings in 2298 ms
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.
^C
mbp:frontend mac$
```
I've created the react app by running `npx created-react-app --template typescript` command. I noticed that error occurs only with `@usedapp/core` library. Is the issue in the package managers (`yarn, npm, npx`)? I've used 3 of them in the same project already.

**Comment by dappdappgo** [comment]
```
...
WARNING in ./node_modules/@usedapp/core/dist/esm/src/providers/transactions/model.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/mac/Developer/DApp/knb/rps/node_modules/@usedapp/core/dist/esm/src/providers/transactions/model.js.map' file: Error: ENOENT: no such file or directory, open '/Users/mac/Developer/DApp/knb/rps/node_modules/@usedapp/core/dist/esm/src/providers/transactions/model.js.map'
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/index.js 10:0-37 10:0-37
 @ ./node_modules/@usedapp/core/dist/esm/src/index.js 2:0-28 2:0-28
 @ ./src/index.tsx 6:0-45 15:33-45

WARNING in ./node_modules/@usedapp/core/dist/esm/src/providers/transactions/provider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/mac/Developer/DApp/knb/rps/node_modules/@usedapp/core/dist/esm/src/providers/transactions/provider.js.map' file: Error: ENOENT: no such file or directory, open '/Users/mac/Developer/DApp/knb/rps/node_modules/@usedapp/core/dist/esm/src/providers/transactions/provider.js.map'
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/DAppProvider.js 8:0-62 50:29-48
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/index.js 1:0-31 1:0-31
 @ ./node_modules/@usedapp/core/dist/esm/src/index.js 2:0-28 2:0-28
 @ ./src/index.tsx 6:0-45 15:33-45
...
```

**Comment by ioitiki** [comment]
Same here
```
WARNING in ./node_modules/@usedapp/core/dist/esm/src/providers/transactions/reducer.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/a/coding/base-erc721-react/node_modules/@usedapp/core/dist/esm/src/providers/transactions/reducer.js.map' file: Error: ENOENT: no such file or directory, open '/Users/a/coding/base-erc721-react/node_modules/@usedapp/core/dist/esm/src/providers/transactions/reducer.js.map'
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/transactions/provider.js 8:0-47 23:46-64
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/DAppProvider.js 8:0-62 50:29-48
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/index.js 1:0-31 1:0-31
 @ ./node_modules/@usedapp/core/dist/esm/src/index.js 2:0-28 2:0-28
 @ ./src/index.js 8:0-54 15:19-34 17:5-20 26:35-47

102 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
```

**Comment by vanruch** [comment]
@vsevdrob @ioitiki @dappdappgo Thanks for reporting, should be fixed in 0.11

**Comment by phanius** [comment]
@vanruch I think issue still persist, I've used 0.11 and new similar warning occur

`WARNING in ./node_modules/@metamask/detect-provider/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/ssd/project/my-app-ts/node_modules/@metamask/detect-provider/src/index.ts' file: Error: ENOENT: no such file or directory, open '/ssd/project/my-app-ts/node_modules/@metamask/detect-provider/src/index.ts'
 @ ./node_modules/@usedapp/core/dist/esm/src/helpers/injectedProvider.js 2:0-63 4:33-55
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/injectedNetwork/provider.js 4:0-69 19:4-23
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/injectedNetwork/index.js 2:0-27 2:0-27
 @ ./node_modules/@usedapp/core/dist/esm/src/providers/index.js 6:0-34 6:0-34
 @ ./node_modules/@usedapp/core/dist/esm/src/index.js 2:0-28 2:0-28
 @ ./src/index.tsx 9:0-59 12:19-37 14:5-16 15:5-23 17:13-16 19:5-16 20:5-23 25:33-45`

if needed, I will open a new issue.
Thank you

**Comment by wsdt** [comment]
Having the same issue..

**Comment by rohansingh20** [comment]
same

**Comment by rzadp** [comment]
```
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/ssd/project/my-app-ts/node_modules/@metamask/detect-provider/src/index.ts' file: Error: ENOENT: no such file or directory, open '/ssd/project/my-app-ts/node_modules/@metamask/detect-provider/src/index.ts'
```

This issue is on the side of `@metamask/detect-provider` - and we are using the latest version, so there is nothing we can do on our side. The issue could be reported to metamask. Also this is just a warning, and should not impact the app in any way for the user.

**Comment by VaishakhKrypC** [comment]
Failed to parse source map from '/app/node_modules/@coinbase/wallet-sdk/node_modules/eth-rpc-errors/src/classes.ts' file: Error: ENOENT: no such file or directory, open '/app/node_modules/@coinbase/wallet-sdk/node_modules/eth-rpc-errors/src/classes.ts'
